### PR TITLE
Use nan to abstract node versions

### PR DESCRIPTION
**Pull request by dtaniwaki**
To support node v0.12.x which breaks the compatibility, we can use [nan](https://github.com/rvagg/nan).

[Review on Reviewable](https://reviewable.io/reviews/isaacs/node-srand/6)

### CODE REVIEW

**Comment by dortzur** [comment]
+1

**Comment by isaacs** [comment]
Seems like this isn't quite working yet?

```
$ npm i

> srand@1.1.4 install /Users/isaacs/dev/js/srand
> node-gyp rebuild

  CXX(target) Release/obj.target/srand/srand.o
../srand.cc:14:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../srand.cc:15:18: error: use of undeclared identifier 'NanNew'
  NanReturnValue(NanNew<Number>(rand()/((double)RAND_MAX + 1)));
                 ^
../srand.cc:15:25: error: 'Number' does not refer to a value
  NanReturnValue(NanNew<Number>(rand()/((double)RAND_MAX + 1)));
                        ^
/Users/isaacs/.node-gyp/5.6.0/deps/v8/include/v8.h:2480:17: note: declared here
class V8_EXPORT Number : public Primitive {
                ^
../srand.cc:19:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../srand.cc:20:18: error: use of undeclared identifier 'NanNew'
  NanReturnValue(NanNew<Integer>(rand()));
                 ^
../srand.cc:20:25: error: 'Integer' does not refer to a value
  NanReturnValue(NanNew<Integer>(rand()));
                        ^
/Users/isaacs/.node-gyp/5.6.0/deps/v8/include/v8.h:2494:17: note: declared here
class V8_EXPORT Integer : public Number {
                ^
../srand.cc:24:3: error: use of undeclared identifier 'NanScope'
  NanScope();
  ^
../srand.cc:25:7: error: use of undeclared identifier 'args'
  if (args.Length() == 0) {
      ^
../srand.cc:26:36: error: use of undeclared identifier 'NanNew'
    NanThrowError(Exception::Error(NanNew<String>("Usage: srand(n)")));
                                   ^
../srand.cc:26:43: error: 'String' does not refer to a value
    NanThrowError(Exception::Error(NanNew<String>("Usage: srand(n)")));
                                          ^
/Users/isaacs/.node-gyp/5.6.0/deps/v8/include/v8.h:2078:17: note: declared here
class V8_EXPORT String : public Name {
                ^
../srand.cc:28:9: error: use of undeclared identifier 'args'
  srand(args[0]->Uint32Value());
        ^
../srand.cc:29:18: error: use of undeclared identifier 'NanUndefined'; did you mean 'Nan::Undefined'?
  NanReturnValue(NanUndefined());
                 ^~~~~~~~~~~~
                 Nan::Undefined
../node_modules/nan/nan.h:521:39: note: 'Nan::Undefined' declared here
  NAN_INLINE v8::Local<v8::Primitive> Undefined() {
                                      ^
../srand.cc:29:3: error: use of undeclared identifier 'NanReturnValue'
  NanReturnValue(NanUndefined());
  ^
../srand.cc:33:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "random", Random);
  ^~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:248:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:236:13: note: candidate function [with TypeName = v8::Local<v8::Object>] not viable: no known conversion from
      'Nan::NAN_METHOD_RETURN_TYPE (Nan::NAN_METHOD_ARGS_TYPE)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd
      argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../srand.cc:34:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "rand", Rand);
  ^~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:248:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:236:13: note: candidate function [with TypeName = v8::Local<v8::Object>] not viable: no known conversion from
      'Nan::NAN_METHOD_RETURN_TYPE (Nan::NAN_METHOD_ARGS_TYPE)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd
      argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../srand.cc:35:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "srand", SRand);
  ^~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:248:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:236:13: note: candidate function [with TypeName = v8::Local<v8::Object>] not viable: no known conversion from
      'Nan::NAN_METHOD_RETURN_TYPE (Nan::NAN_METHOD_ARGS_TYPE)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd
      argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
../srand.cc:36:3: error: no matching function for call to 'NODE_SET_METHOD'
  NODE_SET_METHOD(target, "seed", SRand);
  ^~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:248:25: note: expanded from macro 'NODE_SET_METHOD'
#define NODE_SET_METHOD node::NODE_SET_METHOD
                        ^~~~~~~~~~~~~~~~~~~~~
/Users/isaacs/.node-gyp/5.6.0/src/node.h:236:13: note: candidate function [with TypeName = v8::Local<v8::Object>] not viable: no known conversion from
      'Nan::NAN_METHOD_RETURN_TYPE (Nan::NAN_METHOD_ARGS_TYPE)' to 'v8::FunctionCallback' (aka 'void (*)(const FunctionCallbackInfo<v8::Value> &)') for 3rd
      argument
inline void NODE_SET_METHOD(const TypeName& recv,
            ^
17 errors generated.
make: *** [Release/obj.target/srand/srand.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/isaacs/dev/npm/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/Users/isaacs/dev/npm/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/isaacs/dev/js/srand
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i"
npm ERR! node v5.6.0
npm ERR! npm  v3.7.0
npm ERR! code ELIFECYCLE
npm ERR! srand@1.1.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the srand@1.1.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the srand package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs srand
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls srand
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
```

**Comment by dtaniwaki** [comment]
I updated nan 2.2.0 to support node v5.0.0 and added `.travis.yml` to verify the node versions.
https://travis-ci.org/dtaniwaki/node-srand/builds/108498288

**Comment by isaacs** [comment]
Thanks, @dtaniwaki.  I landed this and published to npm.  I've also added you as a collaborator on this repo, and an author on the npm package.  Feel free to take over, since I don't actually use this, and haven't been very attentive with keeping it up to date :)

**Pull request merged**
